### ISSUE TITLE
Player Login Errors

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#122]
02.04 22:38:47 [Multicraft] Skipped 22 lines due to rate limit (30/s)
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO org.bukkit.event.EventException
02.04 22:38:47 [Server] INFO [22:38:47 ERROR]: Could not pass event PlayerJoinEvent to DarthCraft v2.7
02.04 22:38:47 [Server] INFO ... 13 more
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
02.04 22:38:47 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
02.04 22:38:47 [Server] INFO at sun.reflect.GeneratedMethodAccessor279.invoke(Unknown Source) ~[?:?]
02.04 22:38:47 [Server] INFO at net.darthcraft.dcmod.listeners.PlayerListener.onPlayerLogin(PlayerListener.java:46) ~[?:?]
02.04 22:38:47 [Server] INFO Caused by: java.lang.NullPointerException
02.04 22:38:47 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:413) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:38:47 [Server] INFO org.bukkit.event.EventException
02.04 22:38:47 [Server] INFO [22:38:47 ERROR]: Could not pass event PlayerLoginEvent to DarthCraft v2.7
02.04 22:38:47 [Server] INFO [22:38:47 INFO]: [DarthCraft] [DEBUG] Using: play.darthcraft.net:25565
02.04 22:38:47 [Server] INFO [22:38:46 INFO]: UUID of player JabbaTheJake is 457a0807-ba1c-4bae-8ff8-afae6718f3b6
02.04 22:38:44 [Server] INFO [22:38:44 INFO]: *HOST* k8walker: oh yeah thats mine
02.04 22:38:42 [Server] INFO [22:38:42 INFO]: [Member] skipperjo421: where is we goin?
02.04 22:38:38 [Server] INFO [22:38:38 INFO]: [Member] robstercrazyman2: there is tto many
02.04 22:38:31 [Server] INFO [22:38:31 INFO]: *HOST* k8walker: left click and shift with the fish in your hand
02.04 22:38:23 [Server] INFO [22:38:23 INFO]: *HOST* k8walker: i mean left click..
02.04 22:38:03 [Server] INFO [22:38:03 INFO]: *HOST* k8walker: here ill show you
02.04 22:38:02 [Server] INFO [22:38:02 INFO]: [Member] robstercrazyman2: not working
02.04 22:37:47 [Server] INFO [22:37:47 INFO]: [Premium] cresto630: 10 fis- ^
02.04 22:37:43 [Server] INFO [22:37:43 INFO]: *HOST* k8walker: Shift and right click with that in your hand
02.04 22:37:31 [Server] INFO [22:37:31 INFO]: [Member] robstercrazyman2: how
02.04 22:37:28 [Server] INFO [22:37:28 INFO]: *HOST* k8walker: You can summon a cat
02.04 22:37:28 [Server] INFO [22:37:28 INFO]: [Member] robstercrazyman2: not dead fish
02.04 22:37:22 [Server] INFO [22:37:22 INFO]: [Member] robstercrazyman2: i wanted a cat
02.04 22:37:21 [Server] INFO [22:37:21 INFO]: *HOST* k8walker: Robster
02.04 22:37:18 [Server] INFO [22:37:18 INFO]: [Member] robstercrazyman2: k8
02.04 22:37:09 [Server] INFO [22:37:09 INFO]: [DarthCraft] <ADMIN> k8walker: do you know how tempting it is
02.04 22:36:57 [Server] INFO [22:36:57 INFO]: [Member] robstercrazyman2: are u terying to make me look sillyu
02.04 22:36:47 [Server] INFO [22:36:47 INFO]: [Member] skipperjo421: did u like ireland :3
02.04 22:36:42 [Server] INFO [22:36:42 INFO]: [Member] skipperjo421: ben?
02.04 22:36:35 [Server] INFO [22:36:35 INFO]: *HOST* k8walker: with that in your hand
02.04 22:36:33 [Server] INFO [22:36:33 INFO]: *HOST* k8walker: Okay Robster, hold shift and right click
02.04 22:36:23 [Server] INFO [22:36:23 INFO]: [Admin] wastelanders: it'll be fun ti serve under you :3
02.04 22:36:22 [Server] INFO [22:36:22 INFO]: [Member] skipperjo421: OTP <3
02.04 22:36:17 [Server] INFO [22:36:17 INFO]: *HOST* k8walker: Thanks Dev ;) <3
02.04 22:36:10 [Server] INFO [22:36:10 INFO]: [Admin] wastelanders: oh congrats on the host kate <33
02.04 22:36:06 [Server] INFO [22:36:06 INFO]: [Member] skipperjo421: heyyyyo :D
02.04 22:36:03 [Server] INFO [22:36:03 INFO]: *HOST* k8walker: come to shoppingmall
02.04 22:36:01 [Server] INFO [22:36:01 INFO]: [Admin] wastelanders: hey skipper :D
02.04 22:35:59 [Server] INFO [22:35:59 INFO]: [DarthCraft] <ADMIN> CONSOLE: Play along :)
02.04 22:35:59 [Server] INFO [22:35:59 INFO]: [Member] robstercrazyman2: yes
02.04 22:35:58 [Server] INFO [22:35:58 INFO]: [DarthCraft] <ADMIN> wastelanders: i heard hahaha
02.04 22:35:54 [Server] INFO [22:35:54 INFO]: *HOST* k8walker: Robster
02.04 22:35:53 [Server] INFO [22:35:53 INFO]: [Member] skipperjo421: hey dev
02.04 22:35:50 [Server] INFO [22:35:50 INFO]: [DarthCraft] <ADMIN> CONSOLE: Trolling in progress.
02.04 22:35:47 [Server] INFO [22:35:47 INFO]: cresto630 fell from a high place
02.04 22:35:43 [Server] INFO [22:35:43 INFO]: [Admin] wastelanders: hai
02.04 22:35:43 [Server] INFO [22:35:43 INFO]: *HOST* k8walker: Hey Devon
02.04 22:35:40 [Server] INFO [22:35:40 INFO]: [DarthCraft] <ADMIN> k8walker: Should i actually
02.04 22:35:39 [Server] INFO [22:35:39 INFO]: [Premium] cresto630: hay Dev C:
02.04 22:35:38 [Server] INFO [22:35:38 INFO]: [DarthCraft] [DEBUG] {"stats":{"totalbans":0,"service":{"mcblockit":0,"glizer":0,"minebans":0,"mcbans":0,"mcbouncer":0},"uuid":"ae269ec04e48445883348e4d2fef0b48","username":"wastelanders"},"success":true}
02.04 22:35:38 [Server] INFO [22:35:38 INFO]: [DarthCraft] [DEBUG] http://api.fishbans.com/stats/wastelanders
02.04 22:35:36 [Server] INFO [22:35:36 INFO]: [Member] robstercrazyman2: no i never went to ireland
02.04 22:35:35 [Multicraft] Skipped 22 lines due to rate limit (30/s)
02.04 22:35:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO org.bukkit.event.EventException
02.04 22:35:35 [Server] INFO [22:35:35 ERROR]: Could not pass event PlayerJoinEvent to DarthCraft v2.7
02.04 22:35:35 [Server] INFO ... 13 more
02.04 22:35:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
02.04 22:35:35 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
02.04 22:35:35 [Server] INFO at sun.reflect.GeneratedMethodAccessor279.invoke(Unknown Source) ~[?:?]
02.04 22:35:35 [Server] INFO at net.darthcraft.dcmod.listeners.PlayerListener.onPlayerLogin(PlayerListener.java:46) ~[?:?]
02.04 22:35:35 [Server] INFO Caused by: java.lang.NullPointerException
02.04 22:35:35 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:97) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerList.attemptLogin(PlayerList.java:413) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
02.04 22:35:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.jar:git-Spigot-b8f6402-a646500]

**Comment by Wild1145** [comment]
This is being caused by the vote to play functionality and is possibly due to the fact that it is not actually enabled in config for the server...

**Comment by Wild1145** [comment]
With the latest updates to the plugins it appears this is no longer an issue.
