### ISSUE TITLE
Banip not working

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#137]
Admins are reporting that Banip is not working for names or IP's.

**Comment by Wild1145** [comment]
[20:03:01] [Server thread/INFO]: Wild1145 issued server command: /banip KoopaBoopa Bye
[20:03:02] [Server thread/ERROR]: [DarthCraft] Unknown command error: null
[20:03:02] [Server thread/ERROR]: [DarthCraft] java.lang.NullPointerException
	at net.darthcraft.dcmod.player.Ban.addIp(Ban.java:117)
	at net.darthcraft.dcmod.commands.Command_banip.run(Command_banip.java:96)
	at net.darthcraft.dcmod.DarthCraft.onCommand(DarthCraft.java:264)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:417)
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Unknown Source)

**Comment by Wild1145** [comment]
We will be handling banning in Essentials for the time being as the issue just isnt clear, banning will be re-implemented in the 3.0 release.
