### ISSUE TITLE
Bans not saving now...

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#139]
[21:13:43] [Server thread/INFO]: [DarthCraft] Disabling DarthCraft v2.8
[21:13:43] [Server thread/ERROR]: Error occurred while disabling DarthCraft v2.8 (Is it up to date?)
java.lang.NullPointerException
	at net.darthcraft.dcmod.player.Ban.saveTo(Ban.java:200) ~[?:?]
	at net.darthcraft.dcmod.addons.BanManager.saveBans(BanManager.java:111) ~[?:?]
	at net.darthcraft.dcmod.DarthCraft.onDisable(DarthCraft.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManager.java:458) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.reload(CraftServer.java:713) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot1.8.jar:git-Spigot-dbe012b-61ef214]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

**Comment by Wild1145** [comment]
We will be handling banning in Essentials for the time being as the issue just isnt clear, banning will be re-implemented in the 3.0 release.
