### ISSUE TITLE
Player Source Errors

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#66]
[13:19:03] [User Authenticator #263/INFO]: UUID of player MelonCrafter_PvP is df9de94e-b7a9-4c48-a3ce-66a0061422b8
[13:19:03] [Server thread/INFO]: [DC Visitor Counter] There have been 10130 players that have joined the server.
[13:19:03] [Server thread/INFO]: [DC Visitor Counter] There have been 10130 unique players that have joined the server.
[13:19:03] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to DarthCraft v2.5
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:262) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:147) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
Caused by: java.lang.NullPointerException
	at net.darthcraft.dcmod.listeners.PlayerListener.onPlayerJoinEvent(PlayerListener.java:65) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor643.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_67]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	... 14 more
[13:19:03] [Server thread/INFO]: [DarthCraft] Added new player: MelonCrafter_PvP
[13:19:03] [Server thread/INFO]: MelonCrafter_PvP[/151.231.111.183:60544] logged in with entity id 3232457 at ([world] -595.5, 64.0, -1733.5)
[13:19:03] [pool-53-thread-1/INFO]: Creating empty config: E:\CraftingNetwork\multicraft\servers\server9\plugins\Essentials\userdata\df9de94e-b7a9-4c48-a3ce-66a0061422b8.yml
[13:19:03] [Server thread/WARN]: §4That kit does not exist.

**Comment by Wild1145** [comment]
This is happening on every login that I can see in the log file.

**Comment by Wild1145** [comment]
My mistake. This is linked to the player source setup, not visitor counter.

**Comment by Wild1145** [comment]
Probably being caused by this:

[21:15:31] [Server thread/INFO]: [DarthCraft] Loading DarthCraft v2.5
[21:15:31] [Server thread/ERROR]: com/maxmind/geoip2/exception/GeoIp2Exception initializing DarthCraft v2.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/maxmind/geoip2/exception/GeoIp2Exception
	at net.darthcraft.dcmod.DarthCraft.onLoad(DarthCraft.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:293) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]
Caused by: java.lang.ClassNotFoundException: com.maxmind.geoip2.exception.GeoIp2Exception
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_67]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_67]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_67]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_67]
	... 5 more

**Comment by Wild1145** [comment]
Probably being caused by this:

[22:40:52] [Server thread/INFO]: [DarthCraft] Loading DarthCraft v2.5
[22:40:52] [Server thread/ERROR]: com/maxmind/geoip2/exception/GeoIp2Exception initializing DarthCraft v2.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/maxmind/geoip2/exception/GeoIp2Exception
	at net.darthcraft.dcmod.DarthCraft.onLoad(DarthCraft.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:293) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:739) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: com.maxmind.geoip2.exception.GeoIp2Exception
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 19 more
