### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#75]
Just saw this in logs, need to look at it:

21:15:39] [Server thread/ERROR]: Error occurred while enabling DarthCraft v2.5 (Is it up to date?)
java.lang.NullPointerException
	at net.darthcraft.dcmod.DarthCraft.onEnable(DarthCraft.java:195) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]

**Comment by Wild1145** [comment]
The problem is somewhere with the actual download of the file, so further information will need to be reviewed to see where in there the problem is being caused.

**Comment by Wild1145** [comment]
I think that problem is resolved in my local copy, now we got this...


[22:08:20] [Server thread/ERROR]: com/maxmind/geoip2/exception/GeoIp2Exception initializing DarthCraft v2.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/maxmind/geoip2/exception/GeoIp2Exception
	at net.darthcraft.dcmod.DarthCraft.onLoad(DarthCraft.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:293) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:739) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:23) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: com.maxmind.geoip2.exception.GeoIp2Exception
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot1.8.jar:git-Spigot-b8f6402-a646500]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
	... 19 more
