### ISSUE TITLE
PlayerJoinEvent

### ISSUE THREAD

**Issue by RobinGall2910** [DarthCraft/DarthCraft#95]
[00:24:41 ERROR]: Could not pass event PlayerJoinEvent to DarthCraft v2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:305) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:
272) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [minec
raft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109)
[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [
minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159
) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java
:82) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:8
00) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
16) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
34) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:537) [minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.7.0_76]
Caused by: java.lang.NullPointerException
        at net.darthcraft.dcmod.addons.PlayerSource.getCountryName(PlayerSource.
java:48) ~[?:?]
        at net.darthcraft.dcmod.addons.PlayerSource.onPlayerJoinEvent(PlayerSour
ce.java:66) ~[?:?]
        at net.darthcraft.dcmod.listeners.PlayerListener.onPlayerJoinEvent(Playe
rListener.java:65) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0
_76]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0
_76]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.7.0_76]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:301) ~[minecraft_server.jar:git-Spigot-c3c767f-33d5de3]
        ... 14 more

Any help with this? I'm running this kind of MC Version

[00:25:58 INFO]: This server is running CraftBukkit version git-Spigot-c3c767f-3
3d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[00:25:58 INFO]: Checking version, please wait...
[00:26:00 INFO]: You are 26 version(s) behind

**Comment by Wild1145** [comment]
This is a bug within the DCMod GeoIP system. This is something that I believe is disabled in DCMod (Or should be on the latest branch) due to the issues that I had with it.
